/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package reinas;

import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author hk
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reinas/Dama.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(470, 150, 50, 57);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reinas/Dama.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(470, 180, 50, 57);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reinas/Dama.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(470, 210, 50, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reinas/Dama.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(470, 270, 50, 57);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reinas/Dama.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(470, 310, 50, 57);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reinas/Dama.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(470, 240, 50, 57);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reinas/Tablero.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 410, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ArrayList<Individuo> poblacion = new ArrayList<Individuo>();  
                Reinas R=new Reinas();
                R.principal(poblacion);
                int []reinas=poblacion.get(0).posReina;
                int reina1=R.a_base_diez(reinas[0], reinas[1], reinas[2]);
                int reina2=R.a_base_diez(reinas[3], reinas[4], reinas[5]);
                int reina3=R.a_base_diez(reinas[6], reinas[7], reinas[8]);
                int reina4=R.a_base_diez(reinas[9], reinas[10], reinas[11]);
                int reina5=R.a_base_diez(reinas[12], reinas[13], reinas[14]);
                int reina6=R.a_base_diez(reinas[15], reinas[16], reinas[17]);
                
                Ventana V=new Ventana();
                V.jLabel1.setLocation(reina1*70, 5);
                V.jLabel3.setLocation(reina2*70, 70*1);
                V.jLabel4.setLocation(reina3*70, 70*2);
                V.jLabel5.setLocation(reina4*70, 70*3);
                V.jLabel6.setLocation(reina5*70, 70*4);
                V.jLabel7.setLocation(reina6*70, 70*5);

                V.setSize(425,444);
               // V.jLabel1.setLocation(140, 70);
                V.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
